### PR TITLE
Add port for MSP430X and GCC.

### PR DESCRIPTION
**Pull request by aggarg**
Description
-----------

This was originally contributed here - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/44

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by n9wxu — APPROVED** [review]

**Review by mingyue86010 — APPROVED** [review]

**Comment by Glamhoth** [comment]
Sad that you cut out the original author...

**Comment by hcorg** [comment]
@aggarg by copying and pasting the files to the new repository you have removed the @rphh authorship, which is quite against community building principles. And honestly - it just feels bad - after months of hiatus, pull request gets merged but with other person attributing to have done the work....

Do you plan to add any CONTRIBUTORS.md or something like that could allow for any acknowledge of other peoples work? Or at least use `git commit --author=...` in the future?

**Comment by aggarg** [comment]
Please accept my sincere apologies. I have now amended the commit and corrected the authorship.I will also make sure
to do that for all the future contributions.

Additionally, this PR should never have waited this long and that is bad on our part. We are building the process around
SLA to ensure that no PR ends up waiting that long.

Apologies once again.

-Gaurav

**Comment by hcorg** [comment]
Thanks! I appreciate quick response :) Good luck with the new repository, I hope it will grow nicely

**Pull request merged**
